services:
    nginx:
        image: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./static:/static
            - ./certbot/www:/var/www/certbot
            - ./certbot/data:/etc/letsencrypt
    certbot:
        image: certbot/certbot
        volumes:
            - ./certbot/www:/var/www/certbot
            - ./certbot/data:/etc/letsencrypt
